logging:
  level:
    root: info


app:
  configurations:
    username: ${vcap.services.my_app_creds.credentials.username}
    password: ${vcap.services.my_app_creds.credentials.password}
    url: ${vcap.services.my_app_creds.credentials.serviceUrl}